name: kifu_viewer
description: An application to view Shogi games by loading Kifu files.
publish_to: 'none'
version: 0.2.0+dev1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  file_selector: ^0.8.2
  file_selector_macos: ^0.0.4
  file_selector_windows: ^0.0.2
  file_selector_linux: ^0.0.2
  file_selector_web: ^0.8.1
  menubar:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3
  material_design_icons_flutter: ^5.0.5955-rc.1
  package_info_plus: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flappy_translator: ^2.0.0-nullsafety.2
  flutter_analysis_options:
    git:
      url: https://github.com/defuncart/flutter_analysis_options
      ref: bb711f33f039e353dd7f6c373bb85361ef1739ff
  flutter_launcher_icons:
    git:
      url: https://github.com/dirkbo/flutter_launcher_icons

dependency_overrides:
  shogi:
    git:
      url: https://github.com/defuncart/shogi
      ref: main
  flutter_shogi_board:
    git:
      url: https://github.com/defuncart/flutter_shogi_board
      ref: main

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/OFL.txt
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-RegularLite.otf

flappy_translator:
  input_file_path: "assets_dev/loca/loca.csv"
  output_dir: "lib"
  file_name: "localizations"
  class_name: "AppLocalizations"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false

flutter_icons:
  android: false
  ios: false
  macos: true
  image_path: "assets_dev/icon/icon_macos.png"
