name: kifu_viewer
description: An application to view Shogi games by loading Kifu files.
publish_to: 'none'
version: 0.2.0+dev1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shogi:
  flutter_shogi_board:
  file_selector:
  file_selector_macos:
  file_selector_windows:
  file_selector_linux:
  file_selector_web:
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
  material_design_icons_flutter:
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flappy_translator: ^2.0.0-nullsafety.2
  flutter_lints:
  flutter_launcher_icons:

dependency_overrides:
  shogi:
    git:
      url: https://github.com/defuncart/shogi
      ref: main
  flutter_shogi_board:
    git:
      url: https://github.com/defuncart/flutter_shogi_board
      ref: main

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/OFL.txt
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-RegularLite.otf

flappy_translator:
  input_file_path: "assets_dev/loca/loca.csv"
  output_dir: "lib"
  file_name: "localizations"
  class_name: "AppLocalizations"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets_dev/icon/icon.png"
  macos:
    generate: true
    image_path: "assets_dev/icon/icon_macos.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
