name: kifu_viewer
description: An application to view Shogi games by loading Kifu files.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shogi:
  flutter_shogi_board:
  file_selector:
  file_selector_macos:
  file_selector_windows:
  file_selector_linux:
  file_selector_web:
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/menubar
  material_design_icons_flutter:
  package_info_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  arb_generator:
  flutter_lints: ^5.0.0
  flutter_launcher_icons:
  app_store_screenshots:
    git: 
      url: https://github.com/defuncart/app_store_screenshots

dependency_overrides:
  shogi:
    git:
      url: https://github.com/defuncart/shogi
      ref: main
  flutter_shogi_board:
    git:
      url: https://github.com/defuncart/flutter_shogi_board
      ref: main

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/OFL.txt
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-RegularLite.otf

arb_generator:
  input_filepath: "assets_dev/loca/loca.csv"
  output_directory: "assets_dev/l10n"
  filename_prepend: ""
  csv_settings:
    delimiter: ";"
    base_index: 1

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets_dev/app_icons/app_icon.png"
  macos:
    generate: true
    image_path: "assets_dev/app_icons/app_icon_macos.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256
