// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: prefer_final_fields, public_member_api_docs, prefer_single_quotes, omit_local_variable_types, unnecessary_this

import 'dart:async';

import 'package:flutter/material.dart';

/// A  class generated by flappy_translator package containing localized strings
class AppLocalizations {
  static String get appTitle => _getText('appTitle');

  static String get generalOk => _getText('generalOk');

  static String get homeScreenNoKifu => _getText('homeScreenNoKifu');

  static String get invalidContentPopupTitle =>
      _getText('invalidContentPopupTitle');

  static String get invalidContentPopupDescription =>
      _getText('invalidContentPopupDescription');

  static Map<String, String> _localizedValues;

  static Map<String, String> _enValues = {
    'appTitle': 'Kifu Viewer',
    'generalOk': 'Ok',
    'homeScreenNoKifu':
        'Please select a kifu by opening a file or pasting from clipboard.',
    'invalidContentPopupTitle': 'Error!',
    'invalidContentPopupDescription':
        'No moves found. Are you sure the content is valid?',
  };

  static Map<String, Map<String, String>> _allValues = {
    'en': _enValues,
  };

  AppLocalizations(Locale locale) {
    _locale = locale;
    _localizedValues = null;
  }

  static Locale _locale;

  static String _getText(String key) {
    return _localizedValues[key] ?? '** $key not found';
  }

  static Locale get currentLocale => _locale;

  static String get currentLanguage => _locale.languageCode;

  static Future<AppLocalizations> load(Locale locale) async {
    final translations = AppLocalizations(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<AppLocalizations> load(Locale locale) => AppLocalizations.load(locale);

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
