name: cd_release_on_tag
on:
  push:
    branches:
      - "!*"
    tags:
      - '*'
env:
  BUILD_PATH_MAC: build/macos/Build/Products/Release/
  BUILD_NAME_MAC: Kifu\ Viewer.app
  BUILD_PATH_LINUX: build/linux/release/
  BUILD_NAME_LINUX: kifu_viewer
  BUILD_PATH_WINDOWS: build/windows/runner/
  BUILD_NAME_WINDOWS: kifu_viewer
  ZIP_NAME: kifu_viewer
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.save_link.outputs.url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Save link
        id: save_link
        run: 
          echo "::set-output name=url::${{ steps.create_release.outputs.upload_url }}"
  macos:
    name: Build + Upload macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Install packages
        run:
          flutter pub get
      - name: Enable macOS Support
        run:
          flutter config --enable-macos-desktop
      - name: Build macOS
        run:
          flutter build macos --release
      - name: Construct full zip name 
        run:
          echo "APP_VERSION=$(grep '^version:' pubspec.yaml | awk '{ print $2 }' | cut -d '+' -f 1)" >> $GITHUB_ENV
          echo "ZIP_FULL_NAME=${{ env.ZIP_NAME }}_macos_${{ env.APP_VERSION }}.zip" >> $GITHUB_ENV
      - name: Zip build
        run: |
            cd build/macos/Build/Products/Release/
            zip -r ${{ env.ZIP_FULL_NAME }} ${{ env.BUILD_NAME_MAC }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: build/macos/Build/Products/Release/${{ env.ZIP_FULL_NAME }}
          asset_name: ${{ env.ZIP_FULL_NAME }}
          asset_content_type: application/zip
  linux:
    name: Build + Upload Linux
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Install packages
        run:
          flutter pub get
      - name: Enable Linux Support
        run:
          flutter config --enable-linux-desktop
      - name: Install dependencies for Linux
        run: |
          sudo apt install clang
          sudo apt install ninja-build
          sudo apt install libgtk-3-dev
          sudo apt install libblkid-dev
      - name: Build Linux
        run:
          flutter build linux --release
      - name: Construct full zip name 
        run: 
          echo "APP_VERSION=$(grep '^version:' pubspec.yaml | awk '{ print $2 }' | cut -d '+' -f 1)" >> $GITHUB_ENV
          echo "ZIP_FULL_NAME=${{ env.ZIP_NAME }}_linux_${{ env.APP_VERSION }}.zip" >> $GITHUB_ENV
      - name: Zip build
        run: |
            cd ${{ env.BUILD_PATH_LINUX }}
            mv bundle ${{ env.BUILD_NAME_LINUX }}
            zip -r ${{ env.ZIP_FULL_NAME }} ${{ env.BUILD_NAME_LINUX }}/
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ env.BUILD_PATH_LINUX }}${{ env.ZIP_FULL_NAME }}
          asset_name: ${{ env.ZIP_FULL_NAME }}
          asset_content_type: application/zip
  windows:
    name: Build + Upload Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - name: Install packages
        run:
          flutter pub get
      - name: Enable Windows Support
        run:
          flutter config --enable-windows-desktop
      - name: Build Windows
        run:
          flutter build windows --release
      - name: Construct full zip name 
        run: 
          echo "APP_VERSION=$(grep '^version:' pubspec.yaml | awk '{ print $2 }' | cut -d '+' -f 1)" >> $GITHUB_ENV
          echo "ZIP_FULL_NAME=${{ env.ZIP_NAME }}_windows_${{ env.APP_VERSION }}.zip" >> $GITHUB_ENV
      - name: Zip build
        run: |
            cd ${{ env.BUILD_PATH_WINDOWS }}
            powershell Compress-Archive Release\* ${{ env.ZIP_FULL_NAME }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ env.BUILD_PATH_WINDOWS }}${{ env.ZIP_FULL_NAME }}
          asset_name: ${{ env.ZIP_FULL_NAME }}
          asset_content_type: application/zip
