name: cd_release_on_tag
on:
  push:
    branches:
      - "!*"
    tags:
      - '*'
env:
  BUILD_PATH_MACOS: build/macos/Build/Products/Release/
  BUILD_NAME_MACOS: Kifu\ Viewer.app
  BUILD_PATH_LINUX: build/linux/x64/release/bundle/
  BUILD_NAME_LINUX: kifu_viewer
  BUILD_PATH_WINDOWS: build/windows/x64/runner
  BUILD_NAME_WINDOWS: kifu_viewer
  ARTIFACT_NAME: kifu_viewer
jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.save_link.outputs.url }}
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'dev') }}
          generate_release_notes: false
      - name: Save link
        id: save_link
        run: 
          echo "::set-output name=url::${{ steps.create_release.outputs.upload_url }}"
  macos:
    name: Build + Upload macOS
    runs-on: macos-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Generate ARB files
        run: dart run arb_generator
      - name: Install packages
        run: flutter pub get
      - name: Build macOS
        run: flutter build macos --release
      - name: Construct full artifact name 
        run: echo "ARTIFACT_FULL_NAME=${{ env.ARTIFACT_NAME }}_macos.dmg" >> $GITHUB_ENV
      - name: Create dmg
        run: |
            brew install create-dmg
            cd ${{ env.BUILD_PATH_MACOS }}
            create-dmg \
            --volname "Kifu Viewer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --icon ${{ env.BUILD_NAME_MACOS }} 200 190 \
            --hide-extension ${{ env.BUILD_NAME_MACOS }} \
            --app-drop-link 600 185 \
            "${{ env.ARTIFACT_FULL_NAME }}" \
            ${{ env.BUILD_NAME_MACOS }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: ${{ env.BUILD_PATH_MACOS }}/${{ env.ARTIFACT_FULL_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  linux:
    name: Build + Upload Linux
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Generate ARB files
        run: dart run arb_generator
      - name: Install packages
        run: flutter pub get
      # https://docs.flutter.dev/get-started/install/linux#linux-prerequisites
      - name: Install dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install --fix-missing
          sudo apt-get install clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - name: Build Linux
        run: flutter build linux --release
      - name: Construct full artifact name 
        run: echo "ARTIFACT_FULL_NAME=${{ env.ARTIFACT_NAME }}_linux.zip" >> $GITHUB_ENV
      - name: Create zip
        run: |
            cd ${{ env.BUILD_PATH_LINUX }}
            zip -r ${{ env.ARTIFACT_FULL_NAME }} .
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: ${{ env.BUILD_PATH_LINUX }}/${{ env.ARTIFACT_FULL_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows:
    name: Build + Upload Windows
    runs-on: windows-latest
    needs: create_release
    steps:
      - uses: actions/checkout@v4
      - uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
      - name: Generate ARB files
        run: dart run arb_generator
      - name: Install packages
        run: flutter pub get
      - name: Build Windows
        run: flutter build windows --release
      - name: Create zip
        run: |
            cd ${{ env.BUILD_PATH_WINDOWS }}
            powershell Compress-Archive Release\* ${{ env.ARTIFACT_NAME }}_windows.zip
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ needs.create_release.outputs.tag-name }}
          files: ${{ env.BUILD_PATH_WINDOWS }}/${{ env.ARTIFACT_NAME }}_windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
